"use client";
import Link from "next/link";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowDown, ArrowRight, ArrowUpRight, Check, ChevronDown, CircleDot, FileSearch, Fingerprint, Globe2, Layers3, Link2, LockKeyhole, Network, Radar as RadarIcon, ShieldCheck, Sparkles } from "lucide-react";
import { Scanner } from "./scanner";
import { Radar } from "./radar";
import { ProviderList } from "./provider-list";
const statistics = [
  { label: "Intelligence sources", value: "05", detail: "Independent security providers", tag: "PLANNED", icon: Layers3, color: "green" },
  { label: "Analysis layers", value: "07", detail: "From URL patterns to reputation", tag: "DESIGNED", icon: ScanLayers, color: "blue" },
  { label: "Risk assessment", value: "100", unit: "point", detail: "Weighted, explainable scoring", tag: "PLANNED", icon: RadarIcon, color: "purple" },
  { label: "Website content stored", value: "0", unit: "bytes", detail: "Only the signals that matter", tag: "BY DESIGN", icon: Fingerprint, color: "orange" },
];
function ScanLayers({ size }: { size?: number }) { return <Network size={size} />; }
const defenses = [{ title: "URL input validation", description: "HTTP/S only. No embedded credentials.", active: true }, { title: "Private address blocking", description: "Reject local and reserved IP literals.", active: true }, { title: "DNS-pinned connections", description: "Rebinding-resistant destination checks.", active: false }, { title: "Isolated scan workers", description: "Bounded requests. Verified redirects.", active: false }];
export function HomeContent() {
  const reducedMotion = useReducedMotion();
  return <motion.div initial={reducedMotion ? false : { opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }}>
    <div className="overview-title"><div><h1>Security overview <span className="overview-dot" /></h1><p>Your first line of defense against the unknown.</p></div><Link href="/docs#roadmap" className="version-badge"><span /> Phase 01 <span className="version-divider">/</span> Foundation <ArrowUpRight size={12} /></Link></div>
    <section className="hero"><div className="hero-copy"><div className="hero-eyebrow"><span className="eyebrow-icon"><ShieldCheck size={13} /></span> KNOW WHAT’S BEHIND THE LINK</div><h2>Analyze suspicious links<br />before you <span>trust them.</span></h2><p>Advanced URL and domain threat intelligence in one place.<br className="desktop-break" /> More context. Less uncertainty. Safer decisions.</p><div className="hero-benefits"><span><Layers3 size={13} /> Multi-engine intelligence</span><span className="benefit-separator" /><span><LockKeyhole size={12} /> Privacy-first architecture</span></div></div><Radar /></section>
    <Scanner />
    <section className="statistics-grid" aria-label="Platform architecture statistics">{statistics.map(({ label, value, detail, tag, icon: Icon, color, unit }) => <div className="stat-card" key={label}><div className="stat-top"><span>{label}</span><span className={`stat-icon ${color}`}><Icon size={17} /></span></div><div className="stat-value">{value}{unit && <span>{unit}</span>}<span className="stat-tag">{tag}</span></div><p>{detail}</p><div className={`stat-underline ${color}`} /></div>)}</section>
    <div className="intelligence-grid"><ProviderList /><section className="panel defense-panel"><div className="panel-header"><div><h2><ShieldCheck size={17} /> Secure at every layer</h2><p>Because the scanner should be safe, too.</p></div></div><div className="defense-visual"><div className="defense-line" /><span><Globe2 size={20} /></span><i /><span className="defense-shield"><ShieldCheck size={30} strokeWidth={1.4} /></span><i /><span><LockKeyhole size={19} /></span></div><div className="defense-list">{defenses.map((defense) => <div className="defense-item" key={defense.title}><span className={defense.active ? "defense-check" : "defense-planned"}>{defense.active ? <Check size={12} /> : <CircleDot size={12} />}</span><div><h3>{defense.title}{!defense.active && <small>PLANNED</small>}</h3><p>{defense.description}</p></div></div>)}</div><Link href="/docs#security" className="defense-footer">Explore our security architecture <ArrowUpRight size={13} /></Link></section></div>
    <section className="how-section" id="how-it-works"><div className="section-heading"><div><div className="eyebrow">FROM UNCERTAINTY TO UNDERSTANDING</div><h2>One link. Multiple layers of insight.</h2></div><span className="subtle-tag">THE SCANNING WORKFLOW <ArrowDown size={12} /></span></div><div className="workflow-grid"><div className="workflow-card"><span className="workflow-step">01</span><span className="workflow-icon"><Link2 size={22} /></span><h3>Submit a suspicious link</h3><p>Start with a URL. The engine validates the input before it goes anywhere.</p><span className="workflow-state"><Check size={11} /> Input validation available</span></div><div className="workflow-card"><span className="workflow-step">02</span><span className="workflow-icon"><Layers3 size={22} /></span><h3>Connect the signals</h3><p>DNS, certificates, redirects and independent threat intelligence, brought together.</p><span className="workflow-state planned">Planned · Phases 3–5</span></div><div className="workflow-card"><span className="workflow-step">03</span><span className="workflow-icon"><FileSearch size={22} /></span><h3>Understand the risk</h3><p>An explainable risk score and a clear report. Evidence, not a guessing game.</p><span className="workflow-state planned">Planned · Phases 6–8</span></div></div></section>
    <section className="developer-banner"><span className="banner-icon"><Sparkles size={22} /></span><div><h3>Built for curiosity. Designed to scale.</h3><p>A modular foundation for security teams, developers, and a safer web.</p></div><Link href="/docs">Meet the architecture <ArrowRight size={16} /></Link></section>
    <section className="faq-section"><div><div className="eyebrow">A LITTLE MORE CONTEXT</div><h2>Good questions.<br />Clear answers.</h2><Link href="/docs">Read the documentation <ArrowUpRight size={13} /></Link></div><div className="faq-list">{[{ q: "Does a secure connection mean a safe website?", a: "No. HTTPS encrypts traffic but does not prove that a site is trustworthy. The planned scoring engine combines reputation, URL patterns, DNS, TLS and redirect behavior instead of relying on a single signal." }, { q: "What happens when I submit a URL right now?", a: "The Phase 1 API validates URL syntax and rejects unsafe protocols, credentials and local IP literals. It does not contact the destination, run providers or store a report. A clear message explains that live scanning is not yet enabled." }, { q: "Are my scans public?", a: "No scan data is saved in Phase 1. The database architecture defaults future scans to private. Ownership checks, retention policies and secure persistence must be implemented before scanning is enabled." }, { q: "Can I integrate SentinelScan into my application?", a: "The initial API contracts and OpenAPI document are available now. API key creation, usage quotas and background scanning are scheduled for later phases; these are not live integrations yet." }].map((item) => <details key={item.q}><summary>{item.q}<ChevronDown size={16} /></summary><p>{item.a}</p></details>)}</div></section>
  </motion.div>;
}
